networks:
  microservices-network:
    driver: bridge

services:
  gateway:
    build: api/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gateway_db:5432/gateway_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      CATALOGUE_URL: http://catalogue:8084
      CUSTOMERS_URL: http://costumers:8086
    depends_on:
      - gateway_db
      - catalogue
      - customers
    networks:
      - microservices-network

  gateway_db:
    image: postgres:15
    container_name: gateway_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gateway_db
    ports:
      - 5432:5432
    volumes:
      - gateway_db:/var/lib/postgres
    networks:
      - microservices-network

  catalogue:
    build: microsservices/catalogue
    container_name: catalogue
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalogue_db:5433/catalogue_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - catalogue_db
    networks:
      - microservices-network

  catalogue_db:
    image: postgres:15
    container_name: catalogue_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=catalogue_db
      - PGPORT=5433
    ports:
      - "5433:5433"
    volumes:
      - catalogue_db:/var/lib/postgres
    networks:
      - microservices-network

  customers:
    build: microsservices/customers
    container_name: costumers
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://costumers_db:5438/customer_db
      SPRING_DATASOURCE_USERNAME: micro
      SPRING_DATASOURCE_PASSWORD: commerce
    depends_on:
      - costumers_db
    networks:
      - microservices-network

  costumers_db:
    image: postgres:16
    container_name: costumers_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: micro
      POSTGRES_PASSWORD: commerce
      PGPORT: 5438
    ports:
      - "5438:5438"
    volumes:
      - costumers_db:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  gateway_db:
  catalogue_db:
  costumers_db: