

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: orders
    password: orders
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 'update' para desenvolvimento, 'validate' ou 'none' para produção
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # Deve ser o mesmo issuer-uri do seu 'customers-service' ou servidor de autenticação
          issuer-uri: http://localhost:8081/realms/your-realm # AJUSTE ESTE VALOR

microcommerce:
  services:
    catalogue:
      base-url: http://localhost:8083 # URL base do catalogue-service (ou use service discovery: lb://catalogue-service)
    cart:
      base-url: http://localhost:8082 # URL base do cart-service (ou use service discovery: lb://cart-service)

logging:
  level:
    org.springframework.security: DEBUG
    com.microcommerce.orders: DEBUG


server:
  port: 8084

