spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: recommendations
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8087
catalogue-service:
  url: ${CATALOGUE_API_URL}