export enum ProductType {
  FOOD = "COMIDA",
  BOOK = "LIVRO",
  ELECTRONIC = "ELETRONICO",
  CLOTHING = "ROUPA",
  FURNITURE = "MOVEIS",
  TOY = "BRINQUEDO",
  COSMETIC = "COSMETICO",
  STATIONERY = "PAPELARIA",
  SPORT = "ESPORTE",
  OTHER = "OUTROS",
}
