version: '3.9'

services:
  customers:
    build: .
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer_db
      SPRING_DATASOURCE_USERNAME: customer
      SPRING_DATASOURCE_PASSWORD: customer
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: micro
      POSTGRES_PASSWORD: commerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: