version: '3.9'

services:
  customers:
    build: .
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5438/customer_db
      SPRING_DATASOURCE_USERNAME: micro
      SPRING_DATASOURCE_PASSWORD: commerce
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: micro
      POSTGRES_PASSWORD: commerce
      PGPORT: 5438
    ports:
      - "5438:5438"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: