server:
  port: 8085

spring:
  application:
    name: cart-service

  # --- Configuração do Banco de Dados (PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: cart
    password: cart
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # --- Configuração de Segurança (OAuth2 Resource Server - JWT) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          # Aponta para 'customers-service' (auth) que está na porta 8086
          issuer-uri: http://localhost:8086/realms/your-realm

# --- Service Discovery (Exemplo com Eureka) ---
# Se você estiver usando Eureka e o gateway também, descomente e configure.
# Caso contrário, as URLs diretas abaixo serão usadas.
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/ # Endereço do seu Eureka server
#     register-with-eureka: true
#     fetch-registry: true

# --- Configuração para chamadas ao catalogue-service ---
microcommerce:
  services:
    catalogue:
      base-url: http://localhost:8084
logging:
  level:
    org.springframework.security: DEBUG
    com.microcommerce.cart: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    reactor.netty.http.client: DEBUG # Para WebClient