spring:
  application:
    name: gateway
  datasource:
    url: jdbc:postgresql://${POSTGRESDB_URL}:${POSTGRESDB_LOCAL_PORT}/${POSTGRESDB_DATABASE}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      mvc:
        routes:
          - id: payment
            uri: ${PAYMENTS_URL:http://localhost:8081}
            predicates:
              - Path=/api/payments/**
            filters:
              - name: featureEnabled
                args:
                  feature: payment
          - id: delivery
            uri: ${SHIPPING_URL:http://localhost:8082}
            predicates:
              - Path=/api/delivery/**
            filters:
              - name: featureEnabled
                args:
                  feature: delivery
          - id: orders
            uri: ${ORDERS_URL:http://localhost:8083}
            predicates:
              - Path=/api/orders/**
            filters:
              - name: featureEnabled
                args:
                  feature: orders
          - id: catalogue
            uri: ${CATALOGUE_URL:http://localhost:8084}
            predicates:
              - Path=/api/catalogue/**
            filters:
              - name: featureEnabled
                args:
                  feature: catalogue
          - id: cart
            uri: ${CART_URL:http://localhost:8085}
            predicates:
              - Path=/api/cart/**
            filters:
              - name: featureEnabled
                args:
                  feature: cart
          - id: auth
            uri: ${CUSTOMERS_URL:http://localhost:8086}
            predicates:
              - Path=/api/auth/**, /api/customers/**, /api/service/**, /users/**
          - id: recommendation
            uri: ${RECOMMENDATION_URL:http://localhost:8087}
            predicates:
              - Path=/api/recommendations/**
            filters:
              - name: featureEnabled
                args:
                  feature: recommendation
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
