import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { VStack } from "@chakra-ui/react";
import NavBar from "@/components/ui/navbar";
import { LightMode } from "@/components/ui/color-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Microcommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <LightMode>
            <VStack h={"100vh"} w={"100vw"} bgColor={"white"} align={"start"}>
              <NavBar />
              <VStack p={8} w="full" h="full" align={"flex-start"} overflow={"scroll"}>
                {children}
              </VStack>
            </VStack>
          </LightMode>
        </Provider>
      </body>
    </html>
  );
}
