spring:
    application:
        name: customer-service
    datasource:
        url: jdbc:postgresql://localhost:5438/customer_db
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
    secret: your_jwt_secret_very_secret_and_long_for_security_and_algorithm_HS256
    refreshExpiration: 604800 # in seconds
    expiration: 3600 # in seconds

server:
    port: 8086

