spring:
    application:
        name: customers-service
    datasource:
        url: jdbc:mysql://localhost:3306/customer_db
        username: customer
        password: customer
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
    secret: your_jwt_secret_very_secret_and_long_for_security_and_algorithm_HS256
    refreshExpiration: 604800 # in seconds
    expiration: 3600 # in seconds
    issuer: microcommerce-auth

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

logging:
    level:
        com.microcommerce.customers: DEBUG
        org.springframework.security: DEBUG

server:
    port: 8086
    servlet:
        context-path: /api/auth

